services:
  db:
    image: postgres:17
    container_name: ticketing_db
    environment:
      POSTGRES_USER: ticketing_user
      POSTGRES_PASSWORD: ticketing_pass
      POSTGRES_DB: ticketing_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: ticketing_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://ticketing_user:ticketing_pass@db:5432/ticketing_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: